# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-13 22:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library', '0003_book_book_status'),
        ('book_borrows', '0001_initial'),
        ('users', '0002_baseuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseuser',
            name='book_borrows',
            field=models.ManyToManyField(through='book_borrows.Borrow', to='library.Book'),
        ),
    ]
