# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-13 22:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('library', '0003_book_book_status'),
        ('users', '0002_baseuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Borrow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('RE', 'Regresado'), ('BO', 'En Préstamo'), ('EX', 'Vencido')], default='BO', max_length=2)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library.Book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.BaseUser')),
            ],
            options={
                'verbose_name_plural': 'borrows',
            },
        ),
    ]
