# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-13 22:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_borrows', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow',
            name='start_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
