# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-13 22:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('book_borrows', '0002_auto_20160313_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
