# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-18 00:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_borrows', '0003_auto_20160313_2235'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrow',
            name='rennovations',
            field=models.IntegerField(default=0),
        ),
    ]
